export const ACTION_CONSTANTS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCES: 'SIGNUP_SUCCES',
  SIGNUP_FAILED: 'SIGNUP_FAILED',
};

//actions are simply plain js objects